### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by boniolp** [adrienpetralia/ApplianceDetectionBenchmark#2]
Hi,

In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely. The fix for this issue is available in version 1.13.1. There is a release checker in https://github.com/pytorch/pytorch/issues/89855.

The torch version in the requirement.txt is torch==1.8.1. We should ensure the benchmark works with torch==1.13.1 and update the requirement.txt.

Paul

**Comment by adrienpetralia** [comment]
Done.

Adrien
